#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#wallpaper 
nitrogen --restore &

#Polybar
$HOME/.config/polybar/launch.sh

bspc monitor -d         

bspc config border_width        1
bspc config window_gap          15

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

